<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Survivalcraft_2_Mod_Encryptor</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Engine">
      <HintPath>..\..\..\..\Desktop\Survivalcraft 2 1.9\Engine.dll</HintPath>
    </Reference>
    <Reference Include="EntitySystem">
      <HintPath>..\..\..\..\Desktop\Survivalcraft 2 1.9\EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Survivalcraft">
      <HintPath>..\..\..\..\Desktop\Survivalcraft 2 1.9\Survivalcraft.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
